# 가져올 이미지를 정의
# 기존 node 보다 크기가 작은 alpine으로 가져옴
FROM node:16
# 경로 설정하기
WORKDIR /app
COPY package.json .
# 명령어 실행 (의존성 설치)
RUN yarn install
COPY . .

# 3000번 포트 노출
EXPOSE 3000

# npm start 스크립트 실행
CMD ["yarn", "start"]