version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    image: bhyunnie/lmim:latest
    expose:
      - 9991
    ports:
      - 9991:9999
    container_name: lmim_server

  client:
    build:
      context: ./client
      dockerfile: dockerfile
    image: bhyunnie/lmim_client:5.0
    expose:
      - 3000
    ports:
      - 3000:3000
    container_name: lmim_client
    environment:
      - CHOKIDAR_USEPOLLING=true
