version: "3.8"

services:
  auth_server:
    build:
      context: /server/auth_server
      dockerfile: dockerfile
    ports:
      - 9980:9980
    container_name: lmim_auth_server
    image: bhyunnie/lmim_auth_server:1.0.3

  project_server:
    build:
      context: ./server/project_server
      dockerfile: dockerfile
    ports:
      - 9981:9981
    container_name: lmim_project_server
    image: bhyunnie/lmim_project_server:1.0.3

  upload_server:
    build:
      context: ./server/upload_server
      dockerfile: dockerfile
    ports:
      - 9982:9982
    container_name: lmim_upload_server
    image: bhyunnie/lmim_upload_server:1.0.4

  blockchain_server:
    build:
      context: ./server/blockchain_server
      dockerfile: dockerfile
    ports:
      - 9983:9983
    container_name: lmim_blockchain_server
    image: bhyunnie/lmim_blockchain_server:1.0.8
