version: "3.8"

services:
  auth_server:
    image: lmim/auth_server:latest
    expose:
      - 9991
    ports:
      - 9991:9991
    container_name: lmim_auth_server

blockchain_server:
  image: lmim/blockchain_server:latest
  expose:
    - 9992
  ports:
    - 9992:9992
  container_name: lmim_blockchain_server

client:
  image: lmim/client:latest
  expose:
    - 3000
  ports:
    - 3000:3000
  container_name: lmim_client
  environment:
    - CHOKIDAR_USEPOLLING=true
